name: fila-controla-leds

on:
  push:
    paths:
      - 'fila-controla-leds/main.c'
jobs:
  fila-controla-leds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-wokwi-test@v3
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          test_name: fila-controla-leds
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        with:
          c_file: fila-controla-leds/main.c
          rubric_file: fila-controla-leds/rubric_firmware.yml
        continue-on-error: true
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: fila-controla-leds/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        with:
          c_file: fila-controla-leds/main.c
